services:
  bot:
    build:
      context: .
      dockerfile: ./bot/Dockerfile
    container_name: bot_healthrisk
    env_file:
      - ./bot/.env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: healthrisk
      DB_USER: postgres
      DB_PASS: 1234
      BACKEND_HOST: backend
    restart: unless-stopped
    depends_on:
      - db
      - backend
      - ml_service
    networks:
      - bot_network

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    env_file:
      - ./backend/.env
    container_name: backend_healthrisk
    environment:
      ML_HOST:  ml_service
      DB_HOST:  db
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - bot_network

  ml_service:
    build:
      context: .
      dockerfile: ./ml_service/Dockerfile
    container_name: ml_healthrisk
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8001:8001"
    networks:
      - bot_network

  db:
    image: postgres:18.1-alpine3.22
    container_name: db_healthrisk
    environment:
      POSTGRES_PASSWORD: 1234
      PGUSER: postgres
      POSTGRES_DB: healthrisk
    volumes:
      - data_db:/var/lib/postgresql
    ports:
      - "5433:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", 'pg_isready', "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - bot_network

volumes:
  data_db:

networks:
  bot_network:
    driver: bridge
